apiVersion: apps/v1
kind: Deployment
metadata:
  name: hack-expense-tracker-deployment
  labels:
    app: expense-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
        - name: expense-tracker
          image: minnuantony/expense-tracker:v1
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: expense-db-storage
      volumes:
        - name: expense-db-storage
          persistentVolumeClaim:
            claimName: expense-db-pvc
      
