apiVersion: v1
kind: Service
metadata:
  name: hack-expense-tracker-service   # Added "hack" here
spec:
  type: LoadBalancer
  selector:
    app: expense-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
